# Generated by Django 5.0.4 on 2024-05-09 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReferencesColour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colour', models.CharField(blank=True, default='unknown', max_length=100, null=True, unique=True, verbose_name='Цвет')),
            ],
            options={
                'verbose_name': 'Справочник цвета',
                'verbose_name_plural': 'Справочники цветов',
            },
        ),
        migrations.CreateModel(
            name='ReferencesManufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(blank=True, db_index=True, default='unknown', max_length=100, null=True, unique=True, verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Справочник производителей',
                'verbose_name_plural': 'Справочник производителей',
            },
        ),
        migrations.CreateModel(
            name='ReferencesProduct_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(blank=True, db_index=True, default='unknown', max_length=100, null=True, unique=True, verbose_name='Категория товара')),
            ],
            options={
                'verbose_name': 'Справочник категорий товаров',
                'verbose_name_plural': 'Справочники категорий товаров',
            },
        ),
    ]
