# Generated by Django 5.0.4 on 2024-05-06 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(db_index=True, max_length=100, verbose_name='Производитель')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='Модель')),
                ('price', models.FloatField(db_index=True, default=0.0, verbose_name='Цена')),
                ('photo', models.ImageField(upload_to='', verbose_name='Фотография')),
                ('year_of_release', models.DateField(blank=True, verbose_name='Год выпуска')),
                ('weight', models.FloatField(blank=True, verbose_name='Вес')),
                ('colour', models.CharField(blank=True, max_length=100, verbose_name='Цвет')),
                ('packing_height', models.FloatField(blank=True, verbose_name='Ширина упаковки')),
                ('package_width', models.FloatField(blank=True, verbose_name='Высота упаковки')),
                ('packing_depth', models.FloatField(blank=True, verbose_name='Глубина упаковки')),
                ('packing_volume', models.FloatField(blank=True, verbose_name='Объем упаковки')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'Общие данные',
            },
        ),
    ]
