# Generated by Django 5.0.4 on 2024-05-09 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedded', models.BooleanField(default=False, verbose_name='Встраиваемый')),
                ('number_of_doors', models.IntegerField(blank=True, verbose_name='Количество дверей')),
                ('height', models.FloatField(blank=True, verbose_name='Ширина')),
                ('width', models.FloatField(blank=True, verbose_name='Высота')),
                ('depth', models.FloatField(blank=True, verbose_name='Глубина')),
            ],
            options={
                'verbose_name': 'Холодильник',
                'verbose_name_plural': 'Холодильники',
            },
        ),
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='Модель')),
                ('price', models.FloatField(db_index=True, default=0.0, verbose_name='Цена')),
                ('photo', models.ImageField(upload_to='', verbose_name='Фотография')),
                ('manual', models.FileField(blank=True, upload_to='', verbose_name='Инструкция')),
                ('year_of_release', models.DateField(blank=True, verbose_name='Год выпуска')),
                ('weight', models.FloatField(blank=True, verbose_name='Вес')),
                ('packing_height', models.FloatField(blank=True, verbose_name='Ширина упаковки')),
                ('package_width', models.FloatField(blank=True, verbose_name='Высота упаковки')),
                ('packing_depth', models.FloatField(blank=True, verbose_name='Глубина упаковки')),
                ('packing_volume', models.FloatField(blank=True, verbose_name='Объем упаковки')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'Общие данные',
                'verbose_name_plural': 'Общие данные',
            },
        ),
    ]
