# Generated by Django 5.0.4 on 2024-05-06 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='general',
            options={'verbose_name': 'Общие данные', 'verbose_name_plural': 'Общие данные'},
        ),
        migrations.AddField(
            model_name='general',
            name='manual',
            field=models.FileField(blank=True, upload_to='', verbose_name='Инструкция'),
        ),
    ]
