# Generated by Django 5.0.4 on 2024-05-07 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_general_options_general_manual'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedded', models.BooleanField(default=False, verbose_name='Встраиваемый')),
                ('number_of_doors', models.IntegerField(blank=True, verbose_name='Количество дверей')),
                ('height', models.FloatField(blank=True, verbose_name='Ширина')),
                ('width', models.FloatField(blank=True, verbose_name='Высота')),
                ('depth', models.FloatField(blank=True, verbose_name='Глубина')),
            ],
            options={
                'verbose_name': 'Общие данные',
                'verbose_name_plural': 'Общие данные',
            },
        ),
    ]
